### ISSUE TITLE
CEH to share AMI images

### ISSUE THREAD

**Issue by KatrionaGoldmann** [AMI-trap/AMI-trap-org#3]
To share a subset of labelled AMI images on the sharepoint

**Comment by gls21** [comment]
I have uploaded the East Hendred farm (Ag0+) subset of data to the SharePoint here: 
https://thealanturininstitute.sharepoint.com/:f:/r/sites/Automatedbiodiversitymonitoring/Shared%20Documents/General/AMI_Ag0+_images?csf=1&web=1&e=Rjdpkt

Within the east_hendred folder, there is a 'positive' and a 'negative' folder - these just indicate whether the AMI is positioned somewhere that should be better for biodiversity, and a place it should be worse. Within each of these, there are folders for the dates of the 14th and 15th August. This is because I wanted to collect a whole night's worth of data (i.e. up to midnight on the 14 and after midnight on the 15th). 

I will do the same for the 2 Northampton farms once I've collected the data tomorrow. 

Let me know if there are any issues accessing the data uploaded.

**Comment by gls21** [comment]
Images from Farringdon Oils site in Northampton now also uploaded. Over the 2 sites (4 AMI systems), there are 22452 images. 

https://thealanturininstitute.sharepoint.com/:f:/r/sites/Automatedbiodiversitymonitoring/Shared%20Documents/General/Data/AMI_Ag0+_images/farringdon?csf=1&web=1&e=QpUiK2
